-- MySQL Script generated by MySQL Workbench
-- Wed Aug  5 01:05:22 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema white-label-loyalty-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema white-label-loyalty-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `white-label-loyalty-db` DEFAULT CHARACTER SET utf8 ;
USE `white-label-loyalty-db` ;

-- -----------------------------------------------------
-- Table `white-label-loyalty-db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `white-label-loyalty-db`.`users` (
  `id` VARBINARY(16) NOT NULL,
  `name` VARCHAR(200) NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(1000) NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `white-label-loyalty-db`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `white-label-loyalty-db`.`companies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `register` VARCHAR(45) NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `register_UNIQUE` (`register` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `white-label-loyalty-db`.`benefits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `white-label-loyalty-db`.`benefits` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(60) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `points` FLOAT NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `amount` INT NOT NULL,
  `expiration` DATETIME NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `companies_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_benefits_companies1_idx` (`companies_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_benefits_companies1`
    FOREIGN KEY (`companies_id`)
    REFERENCES `white-label-loyalty-db`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `white-label-loyalty-db`.`users_has_benefits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `white-label-loyalty-db`.`users_has_benefits` (
  `users_id` VARBINARY(16) NOT NULL,
  `benefits_id` INT NOT NULL,
  `points` FLOAT NOT NULL DEFAULT 0.0,
  `updated` DATETIME NOT NULL,
  PRIMARY KEY (`users_id`, `benefits_id`),
  INDEX `fk_users_has_benefits_benefits1_idx` (`benefits_id` ASC),
  INDEX `fk_users_has_benefits_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_benefits_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `white-label-loyalty-db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_benefits_benefits1`
    FOREIGN KEY (`benefits_id`)
    REFERENCES `white-label-loyalty-db`.`benefits` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
