name: white-label-loyalty-app
on:
    push:
        branches:
            - master
            - develop
    pull_request:
        branches:
            - master
            - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test
